# Generated by Django 4.0 on 2021-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='link',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
