# Generated by Django 4.0 on 2021-12-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_orders_link_alter_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='link',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='api_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='primary_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='secrete_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
