# Generated by Django 4.0 on 2021-12-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0005_remove_ticket_message_ticketreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
