# Generated by Django 4.0 on 2022-01-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_ticketreply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='secrete_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
