# Generated by Django 4.0 on 2022-01-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_account_amount_remove_account_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.CharField(default=0.0, max_length=225),
        ),
    ]
