# Generated by Django 4.0 on 2022-01-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'successful')], default=0, max_length=150),
        ),
    ]
