# Generated by Django 4.0 on 2022-01-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_transactions_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='trans_type',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
