# Generated by Django 4.0 on 2022-01-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_transactions_trans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('0', 'pending'), ('1', 'successful'), ('-1', 'failed')], default=0, max_length=150),
        ),
    ]
