# Generated by Django 4.0 on 2022-01-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_transactions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, default=0.0, max_length=225),
        ),
    ]
