# Generated by Django 4.0 on 2022-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_service_duration_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('1', 'approved'), ('0', 'pending'), ('-1', 'expired')], default=0, max_length=10),
        ),
    ]
